const STORY_FILES = [
  "story00.txt",
  "story01.txt",
  "story02.txt",
  "story03.txt",
  "story04.txt",
  "story05.txt",
  "story06.txt",
  "story07.txt",
  "story08.txt",
  "story09.txt",
  "story10.txt",
  "story_close.txt",
] as const;

const SPRITE_FILES = [
  "ax.png",
  "bearman.png",
  "blackbear.png",
  "candle0.png",
  "candle1.png",
  "candle2.png",
  "chas0.png",
  "chas1.png",
  "chas2.png",
  "cloak.png",
  "coldeco.png",
  "epitaph0.png",
  "epitaph1.png",
  "fish00.png",
  "fish01.png",
  "flower0.png",
  "flower1.png",
  "gameover.png",
  "gameover2.png",
  "hell0.png",
  "hell1.png",
  "hell2.png",
  "iceflare.png",
  "inn.png",
  "kudou.png",
  "lighter.png",
  "lucifer.png",
  "memo.png",
  "nazo00.png",
  "noenemy.png",
  "self.png",
  "selfclosed.png",
  "shop.png",
  "snow0.png",
  "snow1.png",
  "snow2.png",
  "snowdoll.png",
  "snowman.png",
  "snowman2.png",
  "snowman3.png",
  "snowman4.png",
  "snowwes.png",
  "snowwes2.png",
  "snowwes3.png",
  "snowwes4.png",
  "warning.png",
  "welcome.png",
  "whitebear.png",
  "whitebear2.png",
  "zereta.png",
] as const;

const CG_FILES = [
  "black.bmp",
  "dark00.bmp",
  "dark01.bmp",
  "dark02.bmp",
  "scene_colde00.bmp",
  "scene_colde01.bmp",
  "scene_engine.bmp",
  "scene_fire.bmp",
  "scene_fireball.bmp",
  "scene_fish.bmp",
  "scene_house00.bmp",
  "scene_house01.bmp",
  "scene_house02.bmp",
  "scene_house03.bmp",
  "scene_kudou.bmp",
  "scene_kudou02.bmp",
  "scene_self00.bmp",
  "scene_self01.bmp",
  "scene_self02.bmp",
  "scene_self03.bmp",
  "scene_self04.bmp",
  "scene_self05.bmp",
  "scene_self06.bmp",
  "scene_self07.bmp",
  "scene_self08.bmp",
  "scene_self09.bmp",
  "scene_self10.bmp",
  "scene_snowball.bmp",
  "scene_white.bmp",
] as const;

const MUSIC_FILES = [
  "coldecot.mp3",
  "fuleuden.mp3",
  "haruyori.mp3",
  "haumu.mp3",
  "macchi.mp3",
  "simoyake.mp3",
  "sironotuiku.mp3",
  "thanatos.mp3",
  "yukimichi.mp3",
  "yukio.mp3",
] as const;

const SOUND_FILES = [
  "break.wav",
  "bub.wav",
  "dh.wav",
  "dun.wav",
  "duty.wav",
  "eat.wav",
  "fire.wav",
  "hyuun.wav",
  "kin.wav",
  "open.wav",
  "popon.wav",
  "roar.wav",
  "spell00.wav",
  "spell01.wav",
  "spell02.wav",
  "spell03.wav",
  "spell04.wav",
  "spell05.wav",
  "spell06.wav",
  "spell07.wav",
  "spell08.wav",
  "spell09.wav",
  "suka.wav",
  "thathatha.wav",
  "turn.wav",
  "up.wav",
  "weak.wav",
  "zurl.wav",
  "step.wav",
] as const;

const STORY_PATHS = [
  ...STORY_FILES,
  ...["zh", "en"].flatMap((locale) =>
    STORY_FILES.map((file) => `${locale}/${file}`)
  ),
];

export const RUNTIME_ASSET_CACHE_NAME = "snow-road-runtime-assets";
export const RUNTIME_ASSET_VERSION_STORAGE_KEY =
  "snow-road-runtime-assets-version";

export const RUNTIME_ASSET_PATHS = [
  ...SPRITE_FILES.map((file) => `sprite/${file}`),
  ...CG_FILES.map((file) => `cg/${file}`),
  ...MUSIC_FILES.map((file) => `music/${file}`),
  ...SOUND_FILES.map((file) => `sound/${file}`),
  ...STORY_PATHS.map((file) => `story/${file}`),
] as const;

export const PRELOAD_IMAGE_ASSET_PATHS = [
  ...SPRITE_FILES.map((file) => `sprite/${file}`),
  ...CG_FILES.map((file) => `cg/${file}`),
];

export const TOTAL_RUNTIME_ASSET_COUNT = RUNTIME_ASSET_PATHS.length;
